### PR TITLE
3 of 4 - Fix wartremover errors

### PR DESCRIPTION
**Pull request by alejandrohdezma**
❗️ ❗️ This PR must be reviewed after #14 has been merged

# What has been done in this PR?

- Add [Wartremover](https://www.wartremover.org) to project
- Suppress false positives inside macro to avoid users encountering them

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
How does this fix this for users?

**Comment by alejandrohdezma** [comment]
By annotating the macro code with `@SuppressWarnings` people using both this library and wartremover won't find those errors in their own code when using the annotation. It's safe to do this since they are all fall-positives and in any case, is "auto-generated" code, so users can't do much about it.

**Comment by ChristopherDavenport** [comment]
How does this expand in a project without wart-remover?

**Comment by alejandrohdezma** [comment]
it doesn't affect at all

**Comment by ChristopherDavenport** [comment]
I'm down for it, but we need to get the CI to pass. Something about an implicit derivation is failing the build.

**Comment by alejandrohdezma** [comment]
Okey dokey, I'll take a look at it

**Comment by alejandrohdezma** [comment]
Now it's failing on `sbt tut` but I don't understand why :(

Do we want to support Scala 2.11.12?

**Comment by ChristopherDavenport** [comment]
I'm fine dropping 2.11 on this repo.

**Pull request merged**
