### PR TITLE
Minimimum library dependencies & reorder

### PR DESCRIPTION
**Pull request by alejandrohdezma**
# What has been done in this PR?

- Remove unneeded dependencies :)
- Change `Meta[Id]` to `def` depending on implicit `Meta[FUUID]`
- Move implicits under `Id.implicits` object
- Add example of `Meta[Id]` recovery

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Need doobie as a dependency for the docs project.

**Comment by alejandrohdezma** [comment]
> Need doobie as a dependency for the docs project.

Added with a few more improvements (check https://github.com/ChristopherDavenport/fuuid-annotation/pull/3#issue-294971248)

**Comment by alejandrohdezma** [comment]
You mean the shapeless tag?

**Comment by ChristopherDavenport** [comment]
Yeah, this needs to actually carry the shapeless dep due to the only way this working is via the tag presently.

**Comment by alejandrohdezma** [comment]
Yep, but since the whole point of this annotation is to provide a tagged `Id` type I think that's a necessary evil :(

**Pull request closed without merging**
